version: "3"

services:
  gadgetplus:
    build: ./
    ports:
      - "3000:3000"
    # depends_on:
    #   - mongodb

  # service2:
  #   build:  # Indent with two spaces
  #     context: ./service2
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3002:3002"