# This is a basic workflow to help you get started with Actions

name: GadgetPlus

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Build 
      run: npm i
      
    - name: Start 
      run: npm run start


    - name: Deploy to AWS EC2 using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          echo "Connected to AWS EC2 instance"
          # cd ~/home/danielwetan/apps/node1
          git pull origin master
          git status
          # cd GadgetPlus
          npm install 
          pm2 start app.js
        
